<?php
$data = array (
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'ĐT THUÊ BAO MẠNG KTF',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '4',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => '25',
    'level' => 0,
    'id' => '16',
    'name' => 'ĐT THUÊ BAO MẠNG KTF',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'Sản phẩm cao cấp',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => 'Sản phẩm cao cấp',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '60',
    'name' => 'Nokia',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '21',
    'name' => 'Hàng Trung Bình',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => 'Hàng Phổ Thông',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'ĐT THẺ MẠNG KTF',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '5',
    'level' => 0,
    'id' => '1',
    'name' => 'ĐT THẺ MẠNG KTF',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Hàng Cao Cấp',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '3',
    'name' => 'Hàng Cao Cấp',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '2',
    'name' => 'Hàng Trung Bình',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => 'Hàng Phổ Thông',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'ĐT THUÊ BAO MẠNG LG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '31',
    'name' => 'ĐT THUÊ BAO MẠNG LG',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'Hàng Cao Cấp',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '32',
    'name' => 'Hàng Cao Cấp',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '36',
    'name' => 'Hàng Trung Bình',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => 'Hàng Phổ Thông',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'ĐT THẺ MẠNG LG',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => 'ĐT THẺ MẠNG LG',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'Hàng Cao Cấp',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => 'Hàng Cao Cấp',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => 'Hàng Trung Bình',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => 'Hàng Phổ Thông',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => 'ĐT THUÊ BAO MẠNG SK',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '37',
    'name' => 'ĐT THUÊ BAO MẠNG SK',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'Hàng Cao Cấp',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '1',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => 'Hàng Cao Cấp',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => 'Hàng Phổ Thông',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => 'Hàng Trung Bình',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'ĐT THẺ MẠNG SK',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => 'ĐT THẺ MẠNG SK',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'Hàng Phổ Thông',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => 'Hàng Phổ Thông',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Hàng Trung Bình',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => 'Hàng Trung Bình',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Hàng Cao Cấp',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => 'Hàng Cao Cấp',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'ĐIỆN THOẠI TRẢ GÓP',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '3',
    'goods_num' => '2',
    'level' => 0,
    'id' => '41',
    'name' => 'ĐIỆN THOẠI TRẢ GÓP',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => 'TRẢ GÓP MẠNG LG',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => 'TRẢ GÓP MẠNG LG',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => 'TRẢ GÓP MẠNG KTF',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '1',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => 'TRẢ GÓP MẠNG KTF',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'TRẢ GÓP MẠNG SK',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => 'TRẢ GÓP MẠNG SK',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'LINH KIỆN & PHỤ KIỆN',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '45',
    'name' => 'LINH KIỆN & PHỤ KIỆN',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'Miếng dán màn hình',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => 'Miếng dán màn hình',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'Pin & Sạc',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => 'Pin & Sạc',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'Máy Thẻ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '50',
    'name' => 'Máy Thẻ',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'Thẻ Điện Thoại',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '57',
    'name' => 'Thẻ Điện Thoại',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'Máy tính để bàn',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '49',
    'name' => 'Máy tính để bàn',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'Laptop',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '46',
    'name' => 'Laptop',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => 'Dell',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Điện gia dụng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '58',
    'name' => 'Điện gia dụng',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'Máy Thuê bao',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '51',
    'name' => 'Máy Thuê bao',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'Máy tính bảng',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '56',
    'name' => 'Máy tính bảng',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'ĐT MANG VỀ VIỆT NAM',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '53',
    'name' => 'ĐT MANG VỀ VIỆT NAM',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'Mạng SK',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => 'Mạng SK',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Mang KTF',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => 'Mang KTF',
  ),
);
?>